name = "gallery-sync-workers"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "LICENSES"
id = "a7a1cf5eb08948a2896fd22122ee313e"
preview_id = "74b624086c4d4dbbbfc91a33cd90bfe7"

[[kv_namespaces]]
binding = "EVENTS"
id = "5d0ef8e87c994d4d8c65c13505f1be4b"
preview_id = "ecce8a5fe05548a09a4c8fbe486e27be"

[vars]
# Non-secret configuration (if needed).
# STRIPE_PRICE_SEATS_BASIC = ""
# STRIPE_PRICE_SEATS_PRO = ""

[env.staging]
name = "gallery-sync-workers-staging"
